### PR TITLE
Test to Replicate Issue ODK-X missing directory

### PR DESCRIPTION
**Pull request by permission-error**
cc @wbrunette @elmps2018

Fixes https://github.com/odk-x/tool-suite-X/issues/440

### CODE REVIEW

**Review by wbrunette — CHANGES_REQUESTED** [review]
@permission-error good start. Your test should have an actual CSV file that it is located there that the system trying to find to recreate the issue. you need to use a pre-existing file on a standard build or LIKELY copy a test file into location and then delete it after the test. All good things to learn about.

**Comment by permission-error** [comment]
@wbrunette tried to refactor the test method to involve the concept of coping a test file. Possibly some more things I need to  do to make it look better

**Review by wbrunette — CHANGES_REQUESTED** [review]
Great job on improving the test.

A couple of points:
1) Please remove your commented out code, we do not want that in the final merge.
2) Add a catch statement before finally and have it indicate a test failure.

For example,  if properties.csv does not exist an exception would be raised in Files copy, and would go the finally statement to clean up. The test would pass and we would not know the test is not running properly.

**Review by wbrunette — APPROVED** [review]

**Comment by wbrunette** [comment]
Test is complete, waiting for appropriate time to merge.

**Comment by wbrunette** [comment]
@permission-error you can consider this successfully complete

**Pull request merged**
