### PR TITLE
Add Navigate View

### PR DESCRIPTION
**Pull request by jbeorse**

### CODE REVIEW

**Comment by clarlars** [comment]
runtests

**Comment by clarlars** [comment]
I am able to make this view crash consistently by rotating the screen.  This could be avoided by moving the accessing of the UI elements to onCreateView or onViewCreated in the NavigateFragment.  I'll review again after the crash is fixed.  Thanks!

**Comment by jbeorse** [comment]
Fixed this issue by moving the initialization logic from onCreate to onActivityCreated

**Comment by clarlars** [comment]
This looks good, but I have a few suggestions.  I think that onOptionsItemSelected in TableDisplayActivity should be changed to not look for filename for the R.id.top_level_table_menu_view_navigate_view case.  I also think that onSetSelectedItemIndex should throw an exception if the fragment type is invalid or at least some sort of log message in case we have fragments trying to erroneously use this function.

**Pull request merged**
